services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: edumap-app-container
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    ports:
      - "8000:80"
      - "5173:5173"
    networks:
      - edumap-network
    env_file:
      - ./.env.docker

  db:
    image: mysql:8.0
    container_name: edumap-db-container
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: edumap
      MYSQL_USER: sail
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password 
    volumes:
      - ./docker-data/db:/var/lib/mysql
    ports:
      - "33061:3306"
    networks:
      - edumap-network

networks:
  edumap-network:
    driver: bridge
volumes:
  docker-data:
    driver: local